"""Add position column to menus table

Revision ID: 2026_04_14_add_position
Revises: 2026_04_13_add_is_folder
Create Date: 2026-04-14

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2026_04_14_add_position'
down_revision = '2026_04_13_add_is_folder'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('position', sa.String(50), nullable=True, server_default='top', comment='菜单位置: top/top_child/left/left_child'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'position')
    # ### end Alembic commands ###
