"""Add is_folder column to menus table

Revision ID: 2026_04_13_add_is_folder
Revises: 2026_04_07_rename_permissions_to_plural
Create Date: 2026-04-13

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2026_04_13_add_is_folder'
down_revision = '2026_04_07_rename_permissions_to_plural'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('is_folder', sa.Boolean(), nullable=True, server_default='0', comment='是否为文件夹'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'is_folder')
    # ### end Alembic commands ###
